version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: liquor_app
    ports:
      - "8502:8502"
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app # Sincroniza tu código local con el contenedor (Hot Reload)


# Nota: Ya no necesitamos declarar 'volumes' globales porque eliminamos 'liquor_data'
